run:
  deadline: 1m

linters:
  disable-all: false
  enable:
    #- funlen
    - dogsled
    - dupl
    - lll
    - whitespace
    - wsl
  presets:
    - bugs
    - unused
    # - style
  fast: false
