version: "2"
run:
  tests: false
linters:
  default: all
  enable:
    - wsl_v5
    - gomodguard_v2
  disable:
    - wsl
    - gomodguard
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - lll
    - mnd
    - musttag
    - nakedret
    - nlreturn
    - nolintlint
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - funlen
  settings:
    nestif:
      min-complexity: 8
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 2
      disable:
        - err
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
