version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - nilnesserr
    - protogetter
    - reassign
    - recvcheck
    - spancheck
    - testifylint
    - whitespace
    - wsl
    - zerologlint
  disable:
    - bodyclose
    - contextcheck
    - funlen
    - musttag
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - (.+)_test\.go
      - internal/config/http_config.go
      - internal/config/config.go
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
