run:
  timeout: 5m

issues.exclude-files:
  - '(.+)_test\.go'
  - 'internal/config/http_config.go'
  - 'internal/config/config.go'
linters:
  disable-all: false
  enable:
    - dogsled
    - dupl
    - whitespace
    - wsl
  disable:
    - funlen
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - musttag
  presets:
    - bugs
    - unused
  fast: false
