# See documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
builds:
  - goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
release:
  github:
    owner: Icinga
    name: check_by_powershell
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
