name: Go
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.18', '1.19' ]

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Go Test
        run: make test

      - name: Go Build
        run: make build

#      - name: Upload artifact
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: check_by_powershell-go${{ matrix.go }}
#          path: build
